spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  server:
    port: 8081


  flyway:
    enabled: true